FROM ruby:latest
MAINTAINER Shiromegane

ENV LANG C.UTF-8
ENV BUILD_PATH /tmp
ENV ROOT_PATH /app

WORKDIR $BUILD_PATH
COPY Gemfile.default $BUILD_PATH/Gemfile
COPY Gemfile.lock $BUILD_PATH/Gemfile.lock

RUN apt-get update -qq && apt-get install -y build-essential mysql-client nodejs && apt-get clean

WORKDIR $ROOT_PATH
COPY . $ROOT_PATH