default: &default
  adapter: mysql2
  collation: <%= ENV['DB_COLLATION'].presence || 'utf8mb4_bin' %>
  encoding: <%= ENV['DB_ENCODING'].presence || 'utf8mb4' %>
  charset: <%= ENV['DB_CHARSET'].presence || 'utf8mb4' %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development: &development
  <<: *default
  host: <%= ENV['DEVELOPMENT_DB_HOST'].presence || 'localhost' %>
  port: <%= ENV['DEVELOPMENT_DB_PORT'].presence || 3306 %>
  database: <%= ENV['DEVELOPMENT_DB_NAME'].presence || 'app_development' %>
  username: <%= ENV['DEVELOPMENT_DB_USERNAME'].presence || 'username' %>
  password: <%= ENV['DEVELOPMENT_DB_PASSWORD'].presence || 'password' %>

test:
  <<: *development
  database: <%= ENV['TEST_DB_NAME'].presence || 'app_test' %>

staging:
  <<: *default
  host: <%= ENV['STAGING_DB_HOST'].presence || 'localhost' %>
  port: <%= ENV['STAGING_DB_PORT'].presence || 3306 %>
  database: <%= ENV['STAGING_DB_NAME'].presence || 'app_staging' %>
  username: <%= ENV['STAGING_DB_USERNAME'].presence || 'username' %>
  password: <%= ENV['STAGING_DB_PASSWORD'].presence || 'password' %>

production:
  <<: *default
  host: <%= ENV['PRODUCTION_DB_HOST'].presence || 'localhost' %>
  port: <%= ENV['PRODUCTION_DB_PORT'].presence || 3306 %>
  database: <%= ENV['PRODUCTION_DB_NAME'].presence || 'app_production' %>
  username: <%= ENV['PRODUCTION_DB_USERNAME'].presence || 'username' %>
  password: <%= ENV['PRODUCTION_DB_PASSWORD'].presence || 'password' %>
